### ISSUE TITLE
 Managed network 

### ISSUE THREAD

**Issue by fjoesne** [basschipper/rancher-homeassistant-catalog#3]
What is the best way to make home-assistant search/discover devices on the hosts' LAN yet have the container use a managed network?

**Comment by basschipper** [comment]
I manually configured al my devices, so I don't know...

Reviewing hassio I think switching to `network_mode: host` could be the solution:
https://github.com/home-assistant/hassio/blob/267791833e95f84ec1b52cd10f6f50dbfa39c027/hassio/docker/homeassistant.py#L61
