### ISSUE TITLE
app not appearing after adding catalog

### ISSUE THREAD

**Issue by alsolh** [basschipper/rancher-homeassistant-catalog#4]
hi, thanks for the efforts, please forgive me as i am still a noob in rancher, when i added the catalog the home assistant app is not appearing, is this catalog compatible with the current version of rancher?

![Screenshot from 2020-06-20 02-31-47](https://user-images.githubusercontent.com/22778662/85184000-2942a880-b29f-11ea-8f2a-0639119b8be7.jpg)
![Screenshot from 2020-06-20 02-32-28](https://user-images.githubusercontent.com/22778662/85184001-2a73d580-b29f-11ea-82f9-aef4abc4041a.jpg)

**Comment by basschipper** [comment]
This is unfortunately a catalogue for Rancher 1.0.
